"""add user connectors

Revision ID: 7e27d0e1d1b7
Revises: bb701d4a8578
Create Date: 2026-09-27 13:08:20.652815

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e27d0e1d1b7"
down_revision: Union[str, Sequence[str], None] = "bb701d4a8578"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_connectors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "provider_user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "provider_username", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("access_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_connectors_provider"),
        "user_connectors",
        ["provider"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_connectors_user_id"), "user_connectors", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_connectors_user_id"), table_name="user_connectors")
    op.drop_index(op.f("ix_user_connectors_provider"), table_name="user_connectors")
    op.drop_table("user_connectors")
    # ### end Alembic commands ###
