"""added memory enabled to user preferences

Revision ID: bb701d4a8578
Revises:
Create Date: 2026-07-25 20:40:08.477925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb701d4a8578'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_prefs', sa.Column('memory_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.alter_column('user_prefs', 'occupation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_prefs', 'baseTone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_sessions', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_sessions', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_user_sessions_is_pinned'), 'user_sessions', ['is_pinned'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_is_pinned'), table_name='user_sessions')
    op.alter_column('user_sessions', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_sessions', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_prefs', 'baseTone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_prefs', 'occupation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user_prefs', 'memory_enabled')
    # ### end Alembic commands ###
