import structlog
from langchain_groq import ChatGroq

from app.db_service.db import get_session
from app.services.agents.github.agent import create_github_agent
from app.services.agent_state import AgentState
from app.utils.config import settings

logger = structlog.get_logger(__name__)


async def executor_node(state: AgentState) -> AgentState:
    """
    Execute the plan generated by planner_node.
    """

    plan = state.get("plan")

    if not plan:
        logger.info("No plan found")
        state["tool_results"] = []
        return state

    results = []

    llm = ChatGroq(
        api_key=settings.GROQ_API_KEY,
        model="openai/gpt-oss-20b",
        max_tokens=2048,
    )

    async for session in get_session():

        for step in plan.steps:

            # No tool means the orchestrator can answer directly.
            if step.tool_name is None:
                continue

            logger.info(
                "Executing plan step",
                step_id=step.step_id,
                tool_name=step.tool_name,
            )

            # -------------------------
            # GitHub Agent
            # -------------------------
            if step.tool_name == "github_agent":

                github_agent = create_github_agent(
                    llm=llm,
                    session=session,
                    user_id=state["user_id"],
                )

                task = step.tool_input.get("task", "")

                result = await github_agent.ainvoke(
                    {
                        "messages": [
                            {
                                "role": "user",
                                "content": task,
                            }
                        ]
                    }
                )

                final_message = result["messages"][-1]

                results.append(
                    {
                        "step_id": step.step_id,
                        "tool_name": step.tool_name,
                        "result": final_message.content,
                    }
                )

            # -------------------------
            # Unknown capability
            # -------------------------
            else:
                logger.warning(
                    "Unknown plan tool",
                    tool_name=step.tool_name,
                )

                results.append(
                    {
                        "step_id": step.step_id,
                        "tool_name": step.tool_name,
                        "result": f"Unsupported tool: {step.tool_name}",
                    }
                )


    state["tool_results"] = results

    return state
